### ISSUE TITLE
Custom Slot Types don't appear in Alexa Tester

### ISSUE THREAD

**Issue by jradwan** [alexa-js/alexa-app-server#24]
I originally logged this against alexa-app ([here](https://github.com/matt-kruse/alexa-app/issues/114))and was told to try moving it here. 

Trying to use a custom slot type, which basically looks like this in my intent:

```
    {
        "slots":{"COMMAND":"COMMAND_SLOT"},
        "utterances":[ "send {the|} {command|} {commands|COMMAND}" ]
    }
```
(where commands is an app.dictionary)

I've also tried:

```
    {
        "slots":{"COMMAND":"COMMAND_SLOT"},
        "utterances":[ "send {the|} {command|} {-|COMMAND}" ]
    }
```

In both cases, the Utterances properly appear in the Alexa Tester (using alexa-app-server 2.3.1), but the Custom Slot Type section of the tester is always empty. I was under the impression the custom slot type info should appear there to facilitate copy/pasting into the interaction model.

I started on alexa-app 2.3.4 and upgraded to 2.4.0 ... same problem.

Thanks!

**Comment by dblock** [comment]
Did you dig this up @jradwan? Is this a bug?

**Comment by jradwan** [comment]
I haven't made any headway on it. My understanding is if I define a custom slot type, it should appear in the Tester? But it doesn't:

![image](https://cloud.githubusercontent.com/assets/11047158/21873129/7a69a2f6-d83a-11e6-9376-ca4287c85384.png)

**Comment by dblock** [comment]
Next steps are to write a test + fix :)

**Comment by tejashah88** [comment]
Actually, it's better suited in alexa-app.

Looking at [this](https://github.com/alexa-js/alexa-app-server/blob/master/index.js#L112) line here, it seems like the custom slots are supposed to be pulled from this function: `app.customSlotTypes()`, where app is an instance of `alexa-app`. The problem here is that according to the latest version of `alexa-app`, this method does not exist.

Either there was an intention to add this so-called method and it never actually happened, or the user is supposed to define the method as part of his/her app. Thoughts?

**Comment by dblock** [comment]
I think it never actually happened. Feel free to implement and PR. Thanks!

**Comment by tejashah88** [comment]
Closing this issue. @dblock Feel free to re-open the issue at alexa-app [here](https://github.com/alexa-js/alexa-app/issues/114).

**Comment by lazerwalker** [comment]
Worth noting that `alexa-app` now supports custom slot type functionality like this: https://github.com/alexa-js/alexa-app/pull/275

Some more work would be needed to expose it for folks who aren't using the new Skill Builder schema. Not something I personally have any interest in doing, but it's available if anyone else has the inclination.
