### ISSUE TITLE
Release 3.0.0

### ISSUE THREAD

**Issue by tejashah88** [alexa-js/alexa-app-server#47]
Considering how many changes we've all contributed to this library, wouldn't it make sense to bump the version to 2.4.0 from 2.3.1, instead of 2.3.2?

**Comment by dblock** [comment]
We should follow semver IMHO. If there're breaking changes, yes. Otherwise quantity of changes shouldn't be a criteria.

**Comment by mreinstein** [comment]
the general rule of them is if you push a new feature or capability but don't break the existing api, you can update the minor version. If you're not adding anything new, not breaking the api, update the patch number.

**Comment by dblock** [comment]
At the very least we're going to require alexa-app >= 2.4.0, so maybe a major bump is warranted here. 

I'm also tempted to release it as 2.5.0, just because that will match alexa-app 2.5.0, but maybe that's unnecessary. Appreciate everybody's thoughts.

Only waiting on #64 to be merged and we can cut a release here.

**Comment by dblock** [comment]
I got some docs in #69, otherwise I feel this is ready to go right on the tail of an alexa-app release (will need to change package.json minimum version for alexa-app).

**Comment by dblock** [comment]
Released as 3.0.0.
